INSTALL_TARGET_PROCESSES = SpringBoard
export GO_EASY_ON_ME = 1

export ARCHS = arm64 arm64e
export TARGET = iphone:clang:13.5:11.0

export PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)

#_THEOS_PACKAGE_DEFAULT_VERSION_FORMAT = $(THEOS_PACKAGE_BASE_VERSION)-$(VERSION.INC_BUILD_NUMBER)$(VERSION.EXTRAVERSION)

include $(THEOS)/makefiles/common.mk
SUBPROJECTS += Tweak #Prefs
SUBPROJECTS += seleniumprefs
include $(THEOS_MAKE_PATH)/aggregate.mk
